/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BackupStatus.java
 *
 * Created on 01.03.2010, 15:10:22
 */
package dimm.home.Panels.Diagnose;

import dimm.home.Rendering.GlossButton;
import dimm.home.Rendering.GlossDialogPanel;
import dimm.home.UserMain;
import home.shared.Utilities.ParseToken;
import home.shared.Utilities.SizeStr;
import home.shared.hibernate.Backup;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author mw
 */
public class BackupStatus extends GlossDialogPanel implements ActionListener
{
    Timer timer;
    Backup object;
    ImageIcon ok_icon;
    ImageIcon nok_icon;
    ImageIcon offline_icon;

    /** Creates new form BackupStatus */
    public BackupStatus(Backup object)
    {
        this.object = object;

        // "ID:%ld TB:%.0lf CB:%.0lf TF:%ld TD:%ld CF:%ld CD:%ld SP:%.0lf STF:%.0lf SCF:%.0lf LT:%.0lf PC:%d",
        initComponents();

        ok_icon = new javax.swing.ImageIcon(getClass().getResource("/dimm/home/images/web_check.png"));
        nok_icon = new javax.swing.ImageIcon(getClass().getResource("/dimm/home/images/web_delete.png"));
        offline_icon = new javax.swing.ImageIcon(getClass().getResource("/dimm/home/images/web_not_selected.png"));

        handle_status();
        
        timer = new Timer(2000, this);

        timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXT_TB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXT_TD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_CB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_CF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_CD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_SP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXT_SPF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TXT_LT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LB_ACTIVE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TXT_NEXT_START = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LB_ACTIVE1 = new javax.swing.JLabel();
        BT_CLOSE = new GlossButton();
        BT_ABORT = new GlossButton();
        BT_START = new GlossButton();

        jPanel1.setOpaque(false);

        jLabel2.setText(UserMain.Txt("Byte_Total")); // NOI18N

        TXT_TB.setEditable(false);
        TXT_TB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText(UserMain.Txt("Files_Total")); // NOI18N

        TXT_TF.setEditable(false);
        TXT_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText(UserMain.Txt("Dirs_Total")); // NOI18N

        TXT_TD.setEditable(false);
        TXT_TD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText(UserMain.Txt("Byte_Total")); // NOI18N

        TXT_CB.setEditable(false);
        TXT_CB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText(UserMain.Txt("Files_checked")); // NOI18N

        TXT_CF.setEditable(false);
        TXT_CF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText(UserMain.Txt("Dirs_checked")); // NOI18N

        TXT_CD.setEditable(false);
        TXT_CD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText(UserMain.Txt("Speed")); // NOI18N

        TXT_SP.setEditable(false);
        TXT_SP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText(UserMain.Txt("Files/s")); // NOI18N

        TXT_SPF.setEditable(false);
        TXT_SPF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText(UserMain.Txt("Ratio")); // NOI18N

        TXT_LT.setEditable(false);
        TXT_LT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText(UserMain.Txt("Active")); // NOI18N

        LB_ACTIVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dimm/home/images/web_not_selected.png"))); // NOI18N
        LB_ACTIVE.setText(" ");

        jLabel1.setText(UserMain.Txt("Next_start")); // NOI18N

        TXT_NEXT_START.setEditable(false);
        TXT_NEXT_START.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText(UserMain.Txt("Last_Result")); // NOI18N

        LB_ACTIVE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dimm/home/images/web_not_selected.png"))); // NOI18N
        LB_ACTIVE1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_CF, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(82, 82, 82)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXT_SPF)
                                .addComponent(TXT_SP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(TXT_NEXT_START, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_ACTIVE1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXT_TD)
                                .addComponent(TXT_TF)
                                .addComponent(TXT_TB, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                            .addComponent(LB_ACTIVE))
                        .addComponent(TXT_LT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TXT_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXT_CF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TXT_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_CD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_TD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TXT_LT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LB_ACTIVE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_SPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXT_NEXT_START, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_ACTIVE1)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        BT_CLOSE.setText(UserMain.Txt("Close")); // NOI18N
        BT_CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CLOSEActionPerformed(evt);
            }
        });

        BT_ABORT.setText(UserMain.Txt("Abort_Backup")); // NOI18N
        BT_ABORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ABORTActionPerformed(evt);
            }
        });

        BT_START.setText(UserMain.Txt("Start_Backup")); // NOI18N
        BT_START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_STARTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_START)
                        .addGap(18, 18, 18)
                        .addComponent(BT_ABORT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(BT_CLOSE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_START)
                    .addComponent(BT_ABORT)
                    .addComponent(BT_CLOSE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_STARTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_STARTActionPerformed
    {//GEN-HEADEREND:event_BT_STARTActionPerformed
        // TODO add your handling code here:
        UserMain.fcc().call_abstract_function("backup CMD:start MA:" + object.getMandant().getId() + " DA:" + object.getDiskArchive().getId() + " BS:" + object.getId());
    }//GEN-LAST:event_BT_STARTActionPerformed

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
        // TODO add your handling code here:
        UserMain.fcc().call_abstract_function("backup CMD:abort MA:" + object.getMandant().getId() + " DA:" + object.getDiskArchive().getId() + " BS:" + object.getId());
    }//GEN-LAST:event_BT_ABORTActionPerformed

    private void BT_CLOSEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_CLOSEActionPerformed
    {//GEN-HEADEREND:event_BT_CLOSEActionPerformed
        // TODO add your handling code here:
        timer.stop();
        this.setVisible(false);
        
    }//GEN-LAST:event_BT_CLOSEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_CLOSE;
    private javax.swing.JButton BT_START;
    private javax.swing.JLabel LB_ACTIVE;
    private javax.swing.JLabel LB_ACTIVE1;
    private javax.swing.JTextField TXT_CB;
    private javax.swing.JTextField TXT_CD;
    private javax.swing.JTextField TXT_CF;
    private javax.swing.JTextField TXT_LT;
    private javax.swing.JTextField TXT_NEXT_START;
    private javax.swing.JTextField TXT_SP;
    private javax.swing.JTextField TXT_SPF;
    private javax.swing.JTextField TXT_TB;
    private javax.swing.JTextField TXT_TD;
    private javax.swing.JTextField TXT_TF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed( ActionEvent e )
    {
        timer.stop();

        try
        {
            if (handle_status())
            {
                LB_ACTIVE.setIcon(ok_icon); 
            }
            else
            {
                LB_ACTIVE.setIcon(offline_icon); 
            }


        }
        catch (Exception exc)
        {
        }
        timer.start();

    }

    @Override
    public void deactivate()
    {
        timer.stop();
    }

    private static final long _1M = 1024*1024;

    private boolean  handle_status()
    {
        String ret = UserMain.fcc().call_abstract_function("backup CMD:status MA:" + object.getMandant().getId() + " DA:" + object.getDiskArchive().getId() + " BS:" + object.getId());
        if (ret == null || ret.charAt(0) != '0')
        {
            return false;
        }

        // "ID:%ld TB:%.0lf CB:%.0lf TF:%ld TD:%ld CF:%ld CD:%ld SP:%.0lf STF:%.0lf SCF:%.0lf LT:%.0lf PC:%d",

        SizeStr str = new SizeStr(0);
        ParseToken pt = new ParseToken(ret);
        if (pt.GetLong("ID:") != 9999)
        {
            long next_start = pt.GetLong("NS:");
            if (next_start > 0)
            {
                Date d = new Date(next_start * 1000);
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss  dd.MM.yyyy");
                TXT_NEXT_START.setText( sdf.format(d));
            }
            
            boolean last_result_ok = pt.GetBoolean("LOK:");
            boolean last_result_nok = pt.GetBoolean("LNOK:");
            ImageIcon img = null;
            if (last_result_ok)
                img = ok_icon;
            else if (last_result_nok)
                img = nok_icon;

            if (LB_ACTIVE1.getIcon() != img)
            {
                LB_ACTIVE1.setIcon(img);
            }



            return false;
        }

        LB_ACTIVE1.setIcon(null);


        TXT_TB.setText( pt.GetLong("TB:").longValue()  + " MB" );
        TXT_CB.setText( pt.GetLong("CB:").longValue()  + " MB" );
        TXT_CD.setText( pt.GetLong("CD:").toString() );
        TXT_TD.setText( pt.GetLong("TD:").toString() );
        TXT_TF.setText( pt.GetLong("TF:").toString() );
        TXT_CF.setText( pt.GetLong("CF:").toString() );

        str.set_size( pt.GetDoubleValue("SP:"));
        TXT_SP.setText( str.toString()  );
        str.set_size( pt.GetDoubleValue("LT:"));
        TXT_LT.setText( str.toString() );
        TXT_SPF.setText( pt.GetLong("STF:").toString() );

        return true;
    }

    @Override
    public JButton get_default_button()
    {
        return BT_CLOSE;
    }
}
