/*
 * EditList.java
 *
 * Created on 25. Dezember 2008, 11:28
 */
package dimm.home;

import dimm.home.Rendering.GlossDialogPanel;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;


/**
 *
 * @author  Administrator
 */



class ListSelectModel extends AbstractListModel
{
    Vector<ListSelectElem> list;

    ListSelectModel(Vector<ListSelectElem> _list)
    {
        list = _list;
    }
    @Override
    public int getSize()
    {
        return list.size();
    }

    @Override
    public Object getElementAt( int index )
    {
        return list.get(index);
    }
}

class ListSelectCellRenderer extends JLabel implements ListCellRenderer
{

    JCheckBox cb = new JCheckBox();

    // This is the only method defined by ListCellRenderer.
    // We just reconfigure the JLabel each time we're called.
    @Override
    public Component getListCellRendererComponent(
            JList list, // the list
            Object value, // value to display
            int index, // cell index
            boolean isSelected, // is the cell selected
            boolean cellHasFocus )    // does the cell have focus
    {
        String s = value.toString();
        cb.setText(s);
        if ( isSelected )
        {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        }
        else
        {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        setEnabled(list.isEnabled());
        setFont(list.getFont());
        setOpaque(true);
        return this;
    }
}

public class EditList extends GlossDialogPanel
{
    Vector<ListSelectElem> not_selected_list;
    Vector<ListSelectElem> selected_list;
    
    private boolean okay;
    
    PropertyChangeListener parent;
    String key;
    
    /** Creates new form EditList */
    public EditList(PropertyChangeListener _parent, String _key, Vector<ListSelectElem> all_available_list, Vector<ListSelectElem> sel)
    {
        initComponents();
        
        parent = _parent;
        key = _key;
        okay = false;
        
        selected_list = sel;
        this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
                

        set_all_available_list( all_available_list );
        
        sort_lists();
        
        this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
        
        this.JL_AVAILABLE.setSelectionMode( ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        this.JL_SELECTED.setSelectionMode(  ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    }
    public void set_all_available_list(Vector<ListSelectElem> all_available_list)
    {
        not_selected_list = new Vector<ListSelectElem>();
        
        // BUILD NOT SELECTED LIST
        for ( int i = 0; i < all_available_list.size(); i++ )
        {
            ListSelectElem listSelectElem = all_available_list.get(i);
            if (selected_list.contains(listSelectElem))
                continue;

            not_selected_list.add(listSelectElem);
        }

        sort_lists();
        
        this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
    
    }
    
    void sort_lists()
    {
        Comparator<ListSelectElem> comp = new Comparator<ListSelectElem>()
        {

            @Override
            public int compare( ListSelectElem l1, ListSelectElem l2 )
            {
                return l1.compare_to( l2 );
            }
        };
        
        Collections.sort( selected_list, comp );
        Collections.sort( not_selected_list, comp );
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_AVAILABLE = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        BT_ADD_ALL = new javax.swing.JButton();
        BT_ADD = new javax.swing.JButton();
        BT_DEL = new javax.swing.JButton();
        BT_DEL_ALL = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_SELECTED = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        BT_OK = new javax.swing.JButton();
        BT_ABORT = new javax.swing.JButton();
        BT_NEW = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(UserMain.getString("Verfuegbar"))); // NOI18N

        JL_AVAILABLE.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        JL_AVAILABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_AVAILABLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JL_AVAILABLE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        BT_ADD_ALL.setText(">>");
        BT_ADD_ALL.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BT_ADD_ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ADD_ALLActionPerformed(evt);
            }
        });

        BT_ADD.setText(">");
        BT_ADD.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BT_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ADDActionPerformed(evt);
            }
        });

        BT_DEL.setText("<");
        BT_DEL.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BT_DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_DELActionPerformed(evt);
            }
        });

        BT_DEL_ALL.setText("<<");
        BT_DEL_ALL.setMargin(new java.awt.Insets(2, 2, 2, 2));
        BT_DEL_ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_DEL_ALLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_ADD_ALL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_DEL_ALL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BT_ADD, BT_ADD_ALL, BT_DEL, BT_DEL_ALL});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BT_ADD_ALL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT_ADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT_DEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT_DEL_ALL)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(UserMain.getString("Ausgewaehlt"))); // NOI18N

        JL_SELECTED.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        JL_SELECTED.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_SELECTEDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JL_SELECTED);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        BT_OK.setText(UserMain.getString("Okay")); // NOI18N
        BT_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_OKActionPerformed(evt);
            }
        });

        BT_ABORT.setText(UserMain.getString("Abbruch")); // NOI18N
        BT_ABORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ABORTActionPerformed(evt);
            }
        });

        BT_NEW.setText(UserMain.getString("Neu...")); // NOI18N
        BT_NEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_NEWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BT_NEW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(BT_ABORT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BT_OK)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BT_ABORT, BT_OK});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_OK)
                    .addComponent(BT_ABORT)
                    .addComponent(BT_NEW))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ABORTActionPerformed
        // TODO add your handling code here:
        okay = false;
        this.setVisible(false);
        
    }//GEN-LAST:event_BT_ABORTActionPerformed

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_OKActionPerformed
        // TODO add your handling code here:
        okay = true;
        this.setVisible(false);
    }//GEN-LAST:event_BT_OKActionPerformed

    private void BT_ADD_ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ADD_ALLActionPerformed
        // TODO add your handling code here:
        selected_list.addAll(not_selected_list);
        not_selected_list.clear();
        
        sort_lists();
        
        this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
        this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
        
        
    }//GEN-LAST:event_BT_ADD_ALLActionPerformed

    private void BT_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ADDActionPerformed
        // TODO add your handling code here:
        int sel_list[] = JL_AVAILABLE.getSelectedIndices();
        
        for ( int i = sel_list.length - 1; i >= 0 ; i-- )
        {
            int idx = sel_list[i];
            ListSelectElem elem = not_selected_list.remove(idx);
            selected_list.add(elem);
        }
        sort_lists();
        this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
        this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
        

    }//GEN-LAST:event_BT_ADDActionPerformed

    private void BT_DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DELActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here://GEN-LAST:event_BT_DELActionPerformed
        int sel_list[] = JL_SELECTED.getSelectedIndices();
        
        for ( int i = sel_list.length - 1; i >= 0 ; i-- )
        {
            int idx = sel_list[i];
            ListSelectElem elem = selected_list.remove(idx);
            not_selected_list.add(elem);
        }
        
        sort_lists();
        
        this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
        this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
        

    }

    private void BT_DEL_ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DEL_ALLActionPerformed
        // TODO add your handling code here:
        not_selected_list.addAll(selected_list);//GEN-LAST:event_BT_DEL_ALLActionPerformed
        selected_list.clear();

        sort_lists();
        
        this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
        this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
        
    }

    private void BT_NEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_NEWActionPerformed
        // TODO add your handling code here:
        parent.propertyChange(new PropertyChangeEvent( this, key, null, null) );
    }//GEN-LAST:event_BT_NEWActionPerformed

    private void JL_AVAILABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_AVAILABLEMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2)
        {
            int idx = JL_AVAILABLE.getSelectedIndex();
        
            ListSelectElem elem = not_selected_list.remove(idx);
            selected_list.add(elem);
            
            sort_lists();
            this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
            this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
            
        }
    }//GEN-LAST:event_JL_AVAILABLEMouseClicked

    private void JL_SELECTEDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_SELECTEDMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2)
        {
            int idx = JL_SELECTED.getSelectedIndex();
        
            ListSelectElem elem = selected_list.remove(idx);
            not_selected_list.add(elem);
            
            sort_lists();
            this.JL_AVAILABLE.setModel(new ListSelectModel(not_selected_list) );
            this.JL_SELECTED.setModel(new ListSelectModel(selected_list) );
            
        }
        
    }//GEN-LAST:event_JL_SELECTEDMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_ADD;
    private javax.swing.JButton BT_ADD_ALL;
    private javax.swing.JButton BT_DEL;
    private javax.swing.JButton BT_DEL_ALL;
    private javax.swing.JButton BT_NEW;
    private javax.swing.JButton BT_OK;
    private javax.swing.JList JL_AVAILABLE;
    private javax.swing.JList JL_SELECTED;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton get_default_button()
    {
        return BT_OK;
    }

    public

    boolean isOkay()
    {
        return okay;
    }
}
