/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SingleTextEditPanel.java
 *
 * Created on 18.09.2009, 16:15:48
 */

package dimm.home.Panels;

import dimm.home.Rendering.*;
import dimm.home.UserMain;
import home.shared.CS_Constants;
import home.shared.hibernate.MailHeaderVariable;
import javax.swing.JButton;

/**
 *
 * @author mw
 */
public class EditHeaderMailVariable extends GlossDialogPanel
{
    private boolean okay;
    /** Creates new form SingleTextEditPanel */
    public EditHeaderMailVariable(String lb)
    {
        initComponents();
        setLabel(lb);
    }

    public String getText()
    {
        return TXT_FELD.getText();
    }
    public void setText(String s)
    {
        TXT_FELD.setText(s);
    }
    public void setLabel(String s)
    {
        LB_FELD.setText(s);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_FELD = new javax.swing.JLabel();
        TXT_FELD = new javax.swing.JTextField();
        BT_OK = new javax.swing.JButton();
        BT_ABORT = new javax.swing.JButton();
        CB_EMAIL = new javax.swing.JCheckBox();
        BT_HELP1 = new GlossButton();

        LB_FELD.setText("jLabel1");

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("dimm/home/MA_Properties"); // NOI18N
        BT_OK.setText(bundle.getString("Okay")); // NOI18N
        BT_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_OKActionPerformed(evt);
            }
        });

        BT_ABORT.setText(bundle.getString("Abort")); // NOI18N
        BT_ABORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ABORTActionPerformed(evt);
            }
        });

        CB_EMAIL.setText(UserMain.Txt("Is_eMail")); // NOI18N

        BT_HELP1.setText(UserMain.Txt("?")); // NOI18N
        BT_HELP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_HELP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BT_HELP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ABORT)
                        .addGap(18, 18, 18)
                        .addComponent(BT_OK))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_FELD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_EMAIL)
                            .addComponent(TXT_FELD, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BT_ABORT, BT_OK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_FELD)
                    .addComponent(TXT_FELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_EMAIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_OK)
                    .addComponent(BT_ABORT)
                    .addComponent(BT_HELP1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
        // TODO add your handling code here:
        okay = true;
        my_dlg.setVisible(false);
    }//GEN-LAST:event_BT_OKActionPerformed

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
        okay = false;
        my_dlg.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ABORTActionPerformed

    private void BT_HELP1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_HELP1ActionPerformed
    {//GEN-HEADEREND:event_BT_HELP1ActionPerformed
        // TODO add your handling code here:
        UserMain.open_help_panel(this.getClass().getSimpleName());
}//GEN-LAST:event_BT_HELP1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_HELP1;
    private javax.swing.JButton BT_OK;
    private javax.swing.JCheckBox CB_EMAIL;
    private javax.swing.JLabel LB_FELD;
    private javax.swing.JTextField TXT_FELD;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton get_default_button()
    {
        return BT_OK;
    }

    /**
     * @return the okay
     */
    public boolean isOkay()
    {
        return okay;
    }

    /**
     * @param okay the okay to set
     */
    public void setOkay( boolean okay )
    {
        this.okay = okay;
    }

    public void setObject( MailHeaderVariable _object )
    {
        TXT_FELD.setText(_object.getVarName());
        CB_EMAIL.setSelected( (_object.getFlags() & CS_Constants.MHV_CONTAINS_EMAIL) == CS_Constants.MHV_CONTAINS_EMAIL);
    }

    public int getFlags()
    {
        return (CB_EMAIL.isSelected() ? CS_Constants.MHV_CONTAINS_EMAIL : 0);
    }

}
