/*
 * LoginPanel.java
 *
 * Created on 22. Mai 2008, 15:05
 */

package dimm.home.Panels;

import dimm.home.Main;
import dimm.home.Preferences;
import dimm.home.Rendering.GlossButton;
import dimm.home.Rendering.GlossDialogPanel;
import dimm.home.Rendering.UI_Generic;
import dimm.home.UserMain;
import javax.swing.JButton;

// Preferences

/**
 
 @author  Administrator
 */
public class PreferencesPanel extends GlossDialogPanel
{
    boolean okay;

    public boolean isOkay()
    {
        return okay;
    }
    
    /** Creates new form LoginPanel */
    public PreferencesPanel()
    {
        initComponents();
        CB_CHECK_NEW.setSelected( Main.get_long_prop(Preferences.CHECK_NEWS) > 0);
        
        COMBO_UI.setSelectedIndex((int)Main.get_long_prop(Preferences.UI, 0l) );

        String l_code = Main.get_prop( Preferences.COUNTRYCODE, "DE");

        if (l_code.compareTo("DE") == 0)
           COMBO_LANG.setSelectedIndex(0);
        if (l_code.compareTo("EN") == 0)
           COMBO_LANG.setSelectedIndex(1);        
    }

    void set()
    {
        String l_code = "DE";
        if (COMBO_LANG.getSelectedIndex() == 1)
        {
            l_code = "EN";
        }
        if (COMBO_LANG.getSelectedIndex() == 0)
        {
            l_code = "DE";
        }
        Main.set_prop( Preferences.COUNTRYCODE, l_code );
        Main.set_long_prop(Preferences.UI, COMBO_UI.getSelectedIndex());
        Main.set_long_prop(Preferences.CHECK_NEWS, CB_CHECK_NEW.isSelected() ? 1 : 0);

        Main.get_prefs().store_props();

        Main.ui = UI_Generic.create_ui( (int)Main.get_long_prop(Preferences.UI, 0l) );
        Main.ui.set_ui(false);

        if (UserMain.self != null)
        {            
            UserMain.self.restart_gui(l_code);            
        }
        else
        {
            UserMain.init_text_interface(l_code);
        }

    }

    
    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_OK = new GlossButton();
        BT_ABORT = new GlossButton();
        jLabel1 = new javax.swing.JLabel();
        COMBO_UI = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        COMBO_LANG = new javax.swing.JComboBox();
        CB_CHECK_NEW = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        BT_OK.setText(UserMain.Txt("Okay")); // NOI18N
        BT_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_OKActionPerformed(evt);
            }
        });

        BT_ABORT.setText(UserMain.Txt("Abbruch")); // NOI18N
        BT_ABORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ABORTActionPerformed(evt);
            }
        });

        jLabel1.setText(UserMain.Txt("Look_n_Feel")); // NOI18N

        COMBO_UI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pirates", "Milk" }));

        jLabel2.setText(UserMain.Txt("Language")); // NOI18N

        COMBO_LANG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deutsch", "English" }));

        CB_CHECK_NEW.setText("  ");
        CB_CHECK_NEW.setOpaque(false);

        jLabel3.setText(UserMain.Txt("CheckNews")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ABORT)
                        .addGap(18, 18, 18)
                        .addComponent(BT_OK))
                    .addComponent(CB_CHECK_NEW)
                    .addComponent(COMBO_UI, 0, 152, Short.MAX_VALUE)
                    .addComponent(COMBO_LANG, 0, 152, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BT_ABORT, BT_OK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(COMBO_LANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(COMBO_UI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CB_CHECK_NEW))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_OK)
                    .addComponent(BT_ABORT))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_OKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_OKActionPerformed
    {//GEN-HEADEREND:event_BT_OKActionPerformed
        // TODO add your handling code here:
        set();
        okay = true;

        this.setVisible(false);
    }//GEN-LAST:event_BT_OKActionPerformed

    private void BT_ABORTActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ABORTActionPerformed
    {//GEN-HEADEREND:event_BT_ABORTActionPerformed
        // TODO add your handling code here:
        okay = false;
        this.setVisible(false);   
    }//GEN-LAST:event_BT_ABORTActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ABORT;
    private javax.swing.JButton BT_OK;
    private javax.swing.JCheckBox CB_CHECK_NEW;
    private javax.swing.JComboBox COMBO_LANG;
    private javax.swing.JComboBox COMBO_UI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton get_default_button()
    {
        return BT_OK;
    }
    
   

   
    
    
}
